version: '3.4'
services:
  product_api:
    image: product_api
    container_name: productapi
    build:
      context: .
      dockerfile: App/ProductAPI/Dockerfile
    restart: on-failure      
    ports:
      - 5000:8001
    depends_on:
      - db
    networks:
      - product_network

  webapp:
    image: webapp
    container_name: webapp
    build:
      context: .
      dockerfile: App/WebApp/Dockerfile
    restart: on-failure      
    ports:
      - 5001:8000
    depends_on: 
      - product_api
    networks: 
      - product_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password%1#29"
      ACCEPT_EULA: "Y"
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    networks:
      - product_network

  test_project:
    image: test_project
    container_name: testproject
    build:
      context: .
      dockerfile: AutomationTests/TestProjectBDD/Dockerfile
    restart: on-failure
    depends_on:
      product_api:
        condition: service_healthy
      selenium-hub:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=remote
    working_dir: /src/AutomationTests/TestProjectBDD
    networks:
      - product_network

  integration_test:
    image: integration_test
    container_name: integrationtest
    build:
      context: .
      dockerfile: AutomationTests/IntegrationTests/Dockerfile
    networks:
      - product_network

  chrome:
    image: selenium/node-chrome:4.19.1-20240402
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_started
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - product_network

  firefox:
    image: selenium/node-firefox:4.19.1-20240402
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_started
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - product_network

  chrome_video:
    image: selenium/video:ffmpeg-6.1-20240402
    volumes:
      - /tmp/videos:/videos
    depends_on:
      chrome:
        condition: service_started
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
    networks:
      - product_network

  firefox_video:
    image: selenium/video:ffmpeg-6.1-20240402
    volumes:
      - /tmp/videos:/videos
    depends_on:
      firefox:
        condition: service_started
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4
    networks:
      - product_network

  selenium-hub:
    image: selenium/hub:4.19.1-20240402
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - product_network

networks:
  product_network:
